// <auto-generated />
namespace LifeLink.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addclientinfoescontrollerandviewbackintoproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addclientinfoescontrollerandviewbackintoproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201610101311539_add clientinfoes controller and view back into project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
