// <auto-generated />
namespace LifeLink.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedaddresstoholdnearestlocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedaddresstoholdnearestlocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201610071412187_updated address to hold nearest location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
